<!DOCTYPE catalogo_productos [
<!ELEMENT catalogo_productos (producto+)>
<!ELEMENT producto (nombre, precio, descripcion?, valoracion?)>
<!ATTLIST producto
id ID #REQUIRED
categoria CDATA #IMPLIED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT valoracion (#PCDATA)>
<!ATTLIST valoracion
puntuacion CDATA #IMPLIED
comentarios CDATA #IMPLIED
>
]>

<catalogo_productos>
    <producto id="33992">
        <nombre>leche</nombre>
        <precio>1,50â‚¬</precio>
        <descripcion>Leche blanca</descripcion>
        <valoracion putuacion="5 estrellas" comentarios="esto es un comentario">Vaya lechaza</valoracion>
    </producto>
</catalogo_productos>